// (c) 1992-2023 Intel Corporation.                            
// Intel, the Intel logo, Intel, MegaCore, NIOS II, Quartus and TalkBack words    
// and logos are trademarks of Intel Corporation or its subsidiaries in the U.S.  
// and/or other countries. Other marks and brands may be claimed as the property  
// of others. See Trademarks on intel.com for full list of Intel trademarks or    
// the Trademarks & Brands Names Database (if Intel) or See www.Intel.com/legal (if Altera) 
// Your use of Intel Corporation's design tools, logic functions and other        
// software and tools, and its AMPP partner logic functions, and any output       
// files any of the foregoing (including device programming or simulation         
// files), and any associated documentation or information are expressly subject  
// to the terms and conditions of the Altera Program License Subscription         
// Agreement, Intel MegaCore Function License Agreement, or other applicable      
// license agreement, including, without limitation, that your use is for the     
// sole purpose of programming logic devices manufactured by Intel and sold by    
// Intel or its authorized distributors.  Please refer to the applicable          
// agreement for further details.                                                 
// Generated by Intel(R) HLS Compiler, Version 23.3.0 Build 92.1

/////////////////////////////////////////////////////////////////
// MODULE zfp_inv_lift_internal
/////////////////////////////////////////////////////////////////
module zfp_inv_lift_internal
(
   input logic clock,
   input logic resetn,
   // AVST in_stream
   input logic in_stream_valid,
   output logic in_stream_ready,
   input logic [63:0] in_stream_data,
   // AVST out_stream
   output logic out_stream_valid,
   input logic out_stream_ready,
   output logic [63:0] out_stream_data,
   input logic start,
   output logic busy,
   output logic done,
   input logic stall
);
   logic resetn_extended;

   // INST zfp_inv_lift_internal of zfp_inv_lift_function_wrapper
   zfp_inv_lift_function_wrapper zfp_inv_lift_internal
   (
      .clock(clock),
      .resetn(resetn_extended),
      // AVST avst_iord_bl_in_stream
      .avst_iord_bl_in_stream_valid(in_stream_valid),
      .avst_iord_bl_in_stream_ready(in_stream_ready),
      .avst_iord_bl_in_stream_data(in_stream_data),
      // AVST avst_iowr_bl_out_stream
      .avst_iowr_bl_out_stream_valid(out_stream_valid),
      .avst_iowr_bl_out_stream_ready(out_stream_ready),
      .avst_iowr_bl_out_stream_data(out_stream_data),
      .start(start),
      .busy(busy),
      .done(done),
      .stall(stall)
   );

   // INST global_reset_extender_inst of acl_reset_handler
   acl_reset_handler
   #(
      .ASYNC_RESET(0),
      .USE_SYNCHRONIZER(0),
      .PULSE_EXTENSION(70),
      .PIPE_DEPTH(0)
   )
   global_reset_extender_inst
   (
      .clk(clock),
      .i_resetn(resetn),
      .o_sclrn(resetn_extended)
   );

endmodule

