// zfp_1d_decompress.v

// Generated using ACDS version 23.3 104

`timescale 1 ps / 1 ps
module zfp_1d_decompress (
		input  wire        clock,            //      clock.clk
		input  wire        resetn,           //      reset.reset_n
		input  wire [63:0] in_stream_data,   //  in_stream.data
		output wire        in_stream_ready,  //           .ready
		input  wire        in_stream_valid,  //           .valid
		output wire [63:0] out_stream_data,  // out_stream.data
		input  wire        out_stream_ready, //           .ready
		output wire        out_stream_valid, //           .valid
		input  wire        start,            //       call.valid
		output wire        busy,             //           .stall
		output wire        done,             //     return.valid
		input  wire        stall             //           .stall
	);

	zfp_1d_decompress_internal zfp_1d_decompress_internal_inst (
		.clock            (clock),            //   input,   width = 1,      clock.clk
		.resetn           (resetn),           //   input,   width = 1,      reset.reset_n
		.in_stream_data   (in_stream_data),   //   input,  width = 64,  in_stream.data
		.in_stream_ready  (in_stream_ready),  //  output,   width = 1,           .ready
		.in_stream_valid  (in_stream_valid),  //   input,   width = 1,           .valid
		.out_stream_data  (out_stream_data),  //  output,  width = 64, out_stream.data
		.out_stream_ready (out_stream_ready), //   input,   width = 1,           .ready
		.out_stream_valid (out_stream_valid), //  output,   width = 1,           .valid
		.start            (start),            //   input,   width = 1,       call.valid
		.busy             (busy),             //  output,   width = 1,           .stall
		.done             (done),             //  output,   width = 1,     return.valid
		.stall            (stall)             //   input,   width = 1,           .stall
	);

endmodule
